### ISSUE TITLE
ReferenceError: hljs is not defined

### ISSUE THREAD

**Issue by fjangfaragesh** [mkrakowitzer/actions-makepdfs#2]
I tried to create a pdf, but the program crashed. The md file contains highlighted JavaScript code.
Without highlighting, the conversion works.
Could it have been forgotten to include the highlight.js library?
```
/makepdfs.js:105
						if (lang && hljs.getLanguage(lang)) {
						            ^

ReferenceError: hljs is not defined
    at Object.highlight (/makepdfs.js:105:19)
    at Object.default_rules.fence (/node_modules/markdown-it/lib/renderer.js:50:27)
    at Renderer.render (/node_modules/markdown-it/lib/renderer.js:326:38)
    at MarkdownIt.render (/node_modules/markdown-it/lib/index.js:543:24)
    at /makepdfs.js:123:19
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

**Comment by nicoppido** [comment]
I have the same issue

> I tried to create a pdf, but the program crashed.

**Comment by mkrakowitzer** [comment]
Should be resolved now. Sorry about this was not getting github notifications.
